[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Christoph Becker", email = "christoph.becker@exb.de"},
]
dependencies = [
    "pytube>=12.1.2",
    "av>=10.0.0",
    "spacy>=3.4.4",
    "pip>=22.3.1",
    "PyMuPDF>=1.21.1",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
