name: Test & Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Python ${{ matrix.python-version }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install --user pdm
          pdm install -G :all
      - name: pytest
        run: pdm run pytest


  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    concurrency: push
    needs: [test]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git checkout main
#    - name: Fetch main
#      run: git fetch --prune origin +refs/heads/main:refs/remotes/origin/main
    - name: Install dependencies
      run: |
        pip install --user pdm
        pdm install -G :all --dev --no-lock --no-editable
        which pdm
    - name: Semantic Release
      run: |
        git config user.email "mail@ch-becker.de"
        git config user.name "Christoph via pipeline"
        pdm run semantic-release publish
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_USERNAME: __token__
        REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}