name: Test & Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Python ${{ matrix.python-version }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install .[test]
          python -m pip install pytest-github-actions-annotate-failures
      - name: pytest
        run: python -m pytest -v tests


  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    concurrency: push
    needs: [test]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ needs.beautify.outputs.new_sha }}
    - name: Fetch master
      run: git fetch --prune origin +refs/heads/master:refs/remotes/origin/master
    - name: Python Semantic Release
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: ${{ secrets.PYPI_USERNAME }}
        repository_password: ${{ secrets.PYPI_PASSWORD }}
